import { Flex } from '@chakra-ui/react';
import Head from 'next/head';

import {
  About,
  Certificate,
  Education,
  Experience,
  Project,
  Skill
} from 'components/Sections';
import Aside from 'components/Aside';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pedro Miguel - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        flexDirection={{
          base: 'column',
          md: 'row'
        }}
      >
        <Aside />
        <Flex flexDirection="column">
          <About />
          <Experience />
          <Education />
          <Skill />
          <Project />
          <Certificate />
        </Flex>
      </Flex>
    </>
  );
}
